### ISSUE TITLE
can not run with npm

### ISSUE THREAD

**Issue by YFJiang** [pawitp/protobuf-decoder#91]
Hello!
when i want to run it by using npm,  I got below errors:"$ npm start

> protobuf-decoder@0.1.0 start
> vite

file:///home/johnson/WorkSpace/node_js/protobuf-decoder-master/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
"

**Comment by pawitp** [comment]
What version of NodeJS are you using? Please try upgrading to the latest LTS if you're using an older version.
